<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PayNexa.Common\PayNexa.Common.csproj" />
  </ItemGroup>

</Project>
