@host = http://localhost:8002
@customerId = 00000000-0000-0000-0000-000000000000

POST {{host}}/api/v1/customers
Content-Type: application/json
X-Correlation-Id: demo-create-customer-001

{
  "firstName": "Saidul Islam",
  "lastName": "Rajib",
  "email": "saidul.is.rajib@gmail.com",
  "phoneNumber": "+8801700000000",
  "dateOfBirth": "1995-05-20"
}

###

GET {{host}}/api/v1/customers/{{customerId}}

###

GET {{host}}/api/v1/customers?page=1&page-size=20&search=rajib&sort-by=created-at&sort-order=desc

###

PUT {{host}}/api/v1/customers/{{customerId}}
Content-Type: application/json

{
  "firstName": "Saidul Islam",
  "lastName": "Rajib",
  "phoneNumber": "+8801700000001"
}

###

GET {{host}}/health/ready
