<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PayNexa.Transactions.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\PayNexa.Caching\PayNexa.Caching.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\PayNexa.Messaging\PayNexa.Messaging.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\PayNexa.MongoDb\PayNexa.MongoDb.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\PayNexa.SqlServer\PayNexa.SqlServer.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\PayNexa.Vault\PayNexa.Vault.csproj" />
    <ProjectReference Include="..\Transaction.Application\Transaction.Application.csproj" />
  </ItemGroup>

</Project>
