@Transaction.API_HostAddress = http://localhost:5069

GET {{Transaction.API_HostAddress}}/health

###

GET {{Transaction.API_HostAddress}}/health/live

###

GET {{Transaction.API_HostAddress}}/health/ready

###
