<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\PayNexa.Common\PayNexa.Common.csproj" />
    <ProjectReference Include="..\Payment.Contracts\Payment.Contracts.csproj" />
    <ProjectReference Include="..\Payment.Domain\Payment.Domain.csproj" />
  </ItemGroup>

</Project>
