@Authentication.API_HostAddress = http://localhost:5111

GET {{Authentication.API_HostAddress}}/health

###

GET {{Authentication.API_HostAddress}}/health/live

###

GET {{Authentication.API_HostAddress}}/health/ready

###
