<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>PayNexa.Authentication.API</RootNamespace>
    <UserSecretsId>paynexa-authentication-api</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.SourceGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\PayNexa.AspNetCore\PayNexa.AspNetCore.csproj" />
    <ProjectReference Include="..\Authentication.Application\Authentication.Application.csproj" />
    <ProjectReference Include="..\Authentication.Infrastructure\Authentication.Infrastructure.csproj" />
  </ItemGroup>

</Project>
