<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PayNexa.Notifications.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\PayNexa.Common\PayNexa.Common.csproj" />
    <ProjectReference Include="..\Notification.Contracts\Notification.Contracts.csproj" />
    <ProjectReference Include="..\Notification.Domain\Notification.Domain.csproj" />
  </ItemGroup>

</Project>
