<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\PayNexa.Common\PayNexa.Common.csproj" />
    <ProjectReference Include="..\Notification.Contracts\Notification.Contracts.csproj" />
    <ProjectReference Include="..\Notification.Domain\Notification.Domain.csproj" />
  </ItemGroup>

</Project>
