<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Services\Authentication\Authentication.Application\Authentication.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Authentication\Authentication.Domain\Authentication.Domain.csproj" />
  </ItemGroup>

</Project>
