<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PayNexa.Customers.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Riok.Mapperly" ExcludeAssets="runtime" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\PayNexa.Common\PayNexa.Common.csproj" />
    <ProjectReference Include="..\Customer.Contracts\Customer.Contracts.csproj" />
    <ProjectReference Include="..\Customer.Domain\Customer.Domain.csproj" />
  </ItemGroup>

</Project>
