<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\PayNexa.Common\PayNexa.Common.csproj" />
    <ProjectReference Include="..\Customer.Contracts\Customer.Contracts.csproj" />
    <ProjectReference Include="..\Customer.Domain\Customer.Domain.csproj" />
  </ItemGroup>

</Project>
