@Notification.API_HostAddress = http://localhost:5122

GET {{Notification.API_HostAddress}}/health

###

GET {{Notification.API_HostAddress}}/health/live

###

GET {{Notification.API_HostAddress}}/health/ready

###
